config/routes.rb
Onlypodcast::Application.routes.draw do
		
	get 'onlypodcast/:episode_num', to: redirect('/%{episode_num}') 
	
	match 'admin', :to => 'access#menu'
    
  match 'feeds/:slug', :to => 'feeds#show', :as => 'feed'
  
  resources :personalities

  resources :podcasts

  resources :episodes, :path => 'id'

  get "home/index"

  match 'all' => 'episodes#list', :as => 'episodes_list'
  
  get ':episode_num', to: 'episodes#feature', as: 'feature'
    
  
  
  

  root :to => 'episodes#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  
  belongs_to :podcast
  
  attr_protected []

	def file_location
		"http://#{HOSTNAME}/files/#{podcast.slug}/#{file_name}"
		
	end
	
	def art_location
		"http://#{HOSTNAME}/files/#{podcast.slug}/#{art_name}"
	end
	
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
	
	before_filter :confirm_logged_in, :except => [:list, :home, :feature]


  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @episodes }
    end
  end

  def list
    @episodes = Episode.all.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @episodes }
    end
  end

  def home
    @episodes = Episode.where(:podcast_id => 1).order('number DESC').limit(3)
  end

  def feature
    @episode = Episode.where(:number => params[:episode_num])[0]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @episode }
    end
  end

  # GET /id/1
  # GET /id/1.json
  def show
    @episode = Episode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @episode }
    end
  end
 
  # GET /episodes/new
  # GET /episodes/new.json
  def new
    @episode = Episode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @episode }
    end
  end

  # GET /episodes/1/edit
  def edit
    @episode = Episode.find(params[:id])
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(params[:episode])

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, :notice => 'Episode was successfully created.' }
        format.json { render :json => @episode, :status => :created, :location => @episode }
      else
        format.html { render :action => "new" }
        format.json { render :json => @episode.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /episodes/1
  # PUT /episodes/1.json
  def update
    @episode = Episode.find(params[:id])

    respond_to do |format|
      if @episode.update_attributes(params[:episode])
        format.html { redirect_to @episode, :notice => 'Episode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @episode.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to episodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_feature.html.erb
<article>

<header class="clearfix">
	<h2><%= link_to "Episode #{episode.number}: #{episode.title}", feature_path(episode.number)%></h2>
	<date><%= episode.date.to_s(:xshort) %></date>

  <img src="<%= episode.art_location %>" />
</header>


<div class="file">
	<audio controls>
	  <source src="<%= episode.file_location %>" type="audio/mpeg">
	Your browser does not support the audio element. Download the file via the link below instead.
	</audio>
	<a href="<%= episode.file_location %>">Download File</a>
</div>

<p class="description">
  <%= episode.description.html_safe %>
</p>

<h3>Show notes:</h3>
<p>
  <%= episode.show_notes.html_safe %>
</p>

</article>

<% if !session[:user_id].blank? %>
	<%= link_to 'Edit', edit_episode_path(episode) %> |
	<%= link_to 'Back', episodes_path %>
<% end %>

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :show_notes %><br />
    <%= f.text_area :show_notes %>
  </div>
  <div class="field">
    <%= f.label :file_name %><br />
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :file_size %><br />
    <%= f.number_field :file_size %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= text_field(:episode, :duration) %>
  </div>
  <div class="field">
    <%= f.label :art_name %><br />
    <%= f.text_field :art_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :xml_subtitle %><br />
    <%= f.text_field :xml_subtitle %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :podcast_id %><br />
    <%= f.number_field :podcast_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/feature.html.erb
<% 
	@page_title = @episode.title 
	@page_description = @episode.description
	@page_image = @episode.art_location
%>
<%= render :partial => 'feature', :locals => {:episode => @episode} %> 

app/views/episodes/home.html.erb
<% @episodes.each do |episode| %>

<%= render :partial => 'feature', :locals => {:episode => episode} %> 

<% end %>

app/views/episodes/index.html.erb
<h3>Listing episodes</h3>

<table>
  <tr>
    <th>Title</th>
    <th>#</th>
    <th>Date</th>
    <th>Duration</th>
    <th>Description</th>
    <th>Keywords</th>
    <th>Podcast</th>
    <th></th>
    <th></th>
    <th></th>
    <th>_id</th>
  </tr>

<% @episodes.each do |episode| %>
  <tr>
    <td><%= episode.title %></td>
    <td><%= episode.number %></td>
    <td><%= episode.date.to_s(:short) %></td>
    <td><%= episode.duration %></td>
    <td><%= episode.description %></td>
    <td><%= episode.keywords %></td>
    <td><%= episode.podcast.slug %></td>
    <td><%= link_to 'Show', episode %></td>
    <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
    <td><%= link_to 'Destroy', episode, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= episode.id %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/list.html.erb
<h2>All Episodes</h2>

<table cellpadding="10" style="max-width:800px; margin:auto">
<% @episodes.each do |episode| %>
  <tr>
    <td><img src="<%= episode.art_location %>" height="100" width="100" /></td>
    <td width="60%"><%= link_to "Ep. #{episode.number}: #{episode.title}", feature_path(episode.number) %><br /><%= episode.description.html_safe %></td>
    <td><%= episode.date.to_s(:xshort) %><br />Duration: <%= episode.duration %></td>
  </tr>
<% end %>
</table>

<br />

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<% 
	@page_title = @episode.title 
	@page_description = @episode.description
%>
<article>

<header class="clearfix">
	<h2>Episode <%= @episode.number %>: <%= @episode.title %></h2>
</header>

<p>
  <b>Date:</b>
  <%= @episode.date.to_s(:long) %>
</p>

<p>
  <b>Art Location</b>
  <%= @episode.art_location %>
</p>

<p>
  <b>File Location</b>
  <%= @episode.file_location %>
</p>

<p>
  <b>Show notes:</b>
  <em>Description</em>: <%= @episode.description.html_safe %><br /><br />
  <em>Notes</em>: <%= @episode.show_notes.html_safe %>
</p>

<p>
  <b>File size:</b>
  <%= @episode.file_size %>
</p>

<p>
  <b>Duration:</b>
  <%= @episode.duration %>
</p>

<p>
  <b>Keywords:</b>
  <%= @episode.keywords %>
</p>

<p>
  <b>Podcast:</b>
  <%= @episode.podcast_id %>
</p>


</article>

<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>