config/routes.rb
Onlypodcast::Application.routes.draw do
		
	get 'onlypodcast/:episode_num', to: redirect('/%{episode_num}') 
	
	match 'admin', :to => 'access#menu'
    
  match 'feeds/:slug', :to => 'feeds#show', :as => 'feed'
  
  resources :personalities

  resources :podcasts

  resources :episodes, :path => 'id'

  get "home/index"

  match 'all' => 'episodes#list', :as => 'episodes_list'
  
  get ':episode_num', to: 'episodes#feature', as: 'feature'
    
  
  
  

  root :to => 'episodes#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/personality.rb
class Personality < ActiveRecord::Base
  #attr_accessible :bio, :first, :image, :last
  attr_protected []

end

app/controllers/personalities_controller.rb
class PersonalitiesController < ApplicationController

  before_filter :confirm_logged_in, :except => [:index, :show]


  # GET /personalities
  # GET /personalities.json
  def index
    @personalities = Personality.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @personalities }
    end
  end

  # GET /personalities/1
  # GET /personalities/1.json
  def show
    @personality = Personality.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @personality }
    end
  end

  # GET /personalities/new
  # GET /personalities/new.json
  def new
    @personality = Personality.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @personality }
    end
  end

  # GET /personalities/1/edit
  def edit
    @personality = Personality.find(params[:id])
  end

  # POST /personalities
  # POST /personalities.json
  def create
    @personality = Personality.new(params[:personality])

    respond_to do |format|
      if @personality.save
        format.html { redirect_to @personality, :notice => 'Personality was successfully created.' }
        format.json { render :json => @personality, :status => :created, :location => @personality }
      else
        format.html { render :action => "new" }
        format.json { render :json => @personality.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /personalities/1
  # PUT /personalities/1.json
  def update
    @personality = Personality.find(params[:id])

    respond_to do |format|
      if @personality.update_attributes(params[:personality])
        format.html { redirect_to @personality, :notice => 'Personality was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @personality.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /personalities/1
  # DELETE /personalities/1.json
  def destroy
    @personality = Personality.find(params[:id])
    @personality.destroy

    respond_to do |format|
      format.html { redirect_to personalities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/personalities_helper.rb
module PersonalitiesHelper
end

app/views/personalities/_form.html.erb
<%= form_for(@personality) do |f| %>
  <% if @personality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personality.errors.count, "error") %> prohibited this personality from being saved:</h2>

      <ul>
      <% @personality.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first %><br />
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br />
    <%= f.text_field :last %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personalities/edit.html.erb
<h1>Editing personality</h1>

<%= render 'form' %>

<%= link_to 'Show', @personality %> |
<%= link_to 'Back', personalities_path %>

app/views/personalities/index.html.erb
<h1>Listing personalities</h1>

<table>
  <tr>
    <th>First</th>
    <th>Last</th>
    <th>Bio</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @personalities.each do |personality| %>
  <tr>
    <td><%= personality.first %></td>
    <td><%= personality.last %></td>
    <td><%= personality.bio %></td>
    <td><%= personality.image %></td>
    <td><%= link_to 'Show', personality %></td>
    <td><%= link_to 'Edit', edit_personality_path(personality) %></td>
    <td><%= link_to 'Destroy', personality, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Personality', new_personality_path %>

app/views/personalities/new.html.erb
<h1>New personality</h1>

<%= render 'form' %>

<%= link_to 'Back', personalities_path %>

app/views/personalities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First:</b>
  <%= @personality.first %>
</p>

<p>
  <b>Last:</b>
  <%= @personality.last %>
</p>

<p>
  <b>Bio:</b>
  <%= @personality.bio %>
</p>

<p>
  <b>Image:</b>
  <%= @personality.image %>
</p>


<%= link_to 'Edit', edit_personality_path(@personality) %> |
<%= link_to 'Back', personalities_path %>