config/routes.rb
Onlypodcast::Application.routes.draw do
		
	get 'onlypodcast/:episode_num', to: redirect('/%{episode_num}') 
	
	match 'admin', :to => 'access#menu'
    
  match 'feeds/:slug', :to => 'feeds#show', :as => 'feed'
  
  resources :personalities

  resources :podcasts

  resources :episodes, :path => 'id'

  get "home/index"

  match 'all' => 'episodes#list', :as => 'episodes_list'
  
  get ':episode_num', to: 'episodes#feature', as: 'feature'
    
  
  
  

  root :to => 'episodes#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  
  has_many :episodes, :order => 'number DESC'
  
  #attr_accessible :author, :category, :description, :explicit, :keywords, :slug, :subcategories, :title, :url
  attr_protected []

end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController

  before_filter :confirm_logged_in, :except => [:index, :show]


  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @podcasts }
    end
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
    @podcast = Podcast.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @podcast }
    end
  end

  # GET /podcasts/new
  # GET /podcasts/new.json
  def new
    @podcast = Podcast.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @podcast }
    end
  end

  # GET /podcasts/1/edit
  def edit
    @podcast = Podcast.find(params[:id])
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(params[:podcast])

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, :notice => 'Podcast was successfully created.' }
        format.json { render :json => @podcast, :status => :created, :location => @podcast }
      else
        format.html { render :action => "new" }
        format.json { render :json => @podcast.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /podcasts/1
  # PUT /podcasts/1.json
  def update
    @podcast = Podcast.find(params[:id])

    respond_to do |format|
      if @podcast.update_attributes(params[:podcast])
        format.html { redirect_to @podcast, :notice => 'Podcast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @podcast.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast = Podcast.find(params[:id])
    @podcast.destroy

    respond_to do |format|
      format.html { redirect_to podcasts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/podcasts/_form.html.erb
<%= form_for(@podcast) do |f| %>
  <% if @podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
      <% @podcast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :explicit %><br />
    <%= f.check_box :explicit %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategories %><br />
    <%= f.text_field :subcategories %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/podcasts/edit.html.erb
<h1>Editing podcast</h1>

<%= render 'form' %>

<%= link_to 'Show', @podcast %> |
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/index.html.erb
<h1>Listing podcasts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Slug</th>
    <th>Url</th>
    <th>Description</th>
    <th>Keywords</th>
    <th>Explicit</th>
    <th>Category</th>
    <th>Subcategories</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @podcasts.each do |podcast| %>
  <tr>
    <td><%= podcast.title %></td>
    <td><%= podcast.slug %></td>
    <td><%= podcast.url %></td>
    <td><%= podcast.description %></td>
    <td><%= podcast.keywords %></td>
    <td><%= podcast.explicit %></td>
    <td><%= podcast.category %></td>
    <td><%= podcast.subcategories %></td>
    <td><%= podcast.author %></td>
    <td><%= link_to 'Show', podcast %></td>
    <td><%= link_to 'Edit', edit_podcast_path(podcast) %></td>
    <td><%= link_to 'Destroy', podcast, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Podcast', new_podcast_path %>

app/views/podcasts/new.html.erb
<h1>New podcast</h1>

<%= render 'form' %>

<%= link_to 'Back', podcasts_path %>

app/views/podcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @podcast.title %>
</p>

<p>
  <b>Slug:</b>
  <%= @podcast.slug %>
</p>

<p>
  <b>Url:</b>
  <%= @podcast.url %>
</p>

<p>
  <b>Description:</b>
  <%= @podcast.description %>
</p>

<p>
  <b>Keywords:</b>
  <%= @podcast.keywords %>
</p>

<p>
  <b>Explicit:</b>
  <%= @podcast.explicit %>
</p>

<p>
  <b>Category:</b>
  <%= @podcast.category %>
</p>

<p>
  <b>Subcategories:</b>
  <%= @podcast.subcategories %>
</p>

<p>
  <b>Author:</b>
  <%= @podcast.author %>
</p>


<%= link_to 'Edit', edit_podcast_path(@podcast) %> |
<%= link_to 'Back', podcasts_path %>