config/routes.rb
Onlypodcast::Application.routes.draw do
		
	get 'onlypodcast/:episode_num', to: redirect('/%{episode_num}') 
	
	match 'admin', :to => 'access#menu'
    
  match 'feeds/:slug', :to => 'feeds#show', :as => 'feed'
  
  resources :personalities

  resources :podcasts

  resources :episodes, :path => 'id'

  get "home/index"

  match 'all' => 'episodes#list', :as => 'episodes_list'
  
  get ':episode_num', to: 'episodes#feature', as: 'feature'
    
  
  
  

  root :to => 'episodes#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width">
  
  <title>The Only Podcast on the Internet<%= @page_title ? ' - ' + @page_title : '' %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  

<meta property='og:image' content="<%= @page_image ? @page_image : $site_image %>" />
<meta property='og:url' content="<%= request.protocol+request.host_with_port+request.fullpath %>" />
<meta property='og:title' content="The Only Podcast on the Internet<%= @page_title ? ': ' + CGI::escapeHTML(@page_title) : '' %>" />
<meta property='og:description' content="<%= @page_description ? CGI::escapeHTML(strip_tags(@page_description)) : Podcast.first.description %>" />

<script>

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41550224-1', 'theonlypodcastontheinternet.com');
  ga('send', 'pageview');


</script>    
</head>
<body>
	<% if !flash[:notice].blank? %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>
	<header><h1><%= link_to 'The Only Podcast on the Internet', root_url %></h1></header>
    <div class="feed"><%= link_to 'Subscribe to the show', feed_path('onlypodcast') %></div>
    <div class="feed"><a href="https://itunes.apple.com/us/podcast/only-podcast-on-internet/id659738651?mt=2">Subscribe in iTunes</a></div>
	
<%= yield %>

</body>
</html>